### ISSUE TITLE
スケジューラを使う

### ISSUE THREAD

**Issue by Tamrin007** [PiroHiroPiro/weather_bot_for_slack#2]
https://www.npmjs.com/package/node-schedule みたいな

**Comment by PiroHiroPiro** [comment]
変更しました！

**Comment by Tamrin007** [comment]
![LGTM](http://hisaichilgtm.herokuapp.com/http://67.media.tumblr.com/ec1b9f9db9a830a5d698ec2cb94ac0a4/tumblr_odidtnPVDH1v0bi87o1_500.gif)
